 import './assets/style/Rules.scss'
 import './assets/style/template-a4-1.scss'
 import './assets/style/template-a4-2.scss'
import './assets/style/template-a4-3.scss'
 import './assets/style/template-a4-4.scss'
 import './assets/style/template-a4-5.scss'
import './assets/style/template-a4-6.scss'
 import './assets/style/template-a4-7.scss'
 import './assets/style/template-a4-8.scss'
 import './assets/style/template-a4-9.scss'
import './assets/style/template-a4-10.scss'
import './assets/style/template-a4-11.scss'

import './image-2.png'
import './image-3.png'
import './bg.png'

import './assets/style/template-a4-4.scss'
 import './assets/style/template-a4-12.scss'
 import './assets/style/template-a4-13.scss'
 import './assets/style/template-a4-14.scss'
import './assets/style/template-a4-15.scss'
 import './assets/style/template-a4-16.scss'
import './assets/style/template-a4-17.scss'
 import './assets/style/template-a4-18.scss'
 import './assets/style/template-a4-19.scss'

 import './assets/style/template-a4-20.scss'

